# Generated by Django 5.2.5 on 2025-09-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'permissions': [('ca_assign_issue', 'Can assign issue to developers')]},
        ),
    ]
