# Generated by Django 5.2.5 on 2025-09-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('qa', 'QA Agent'), ('dev', 'Developer')], default='qa', help_text='Select role: QA Agent or Developer', max_length=20, null=True),
        ),
    ]
